# Generated by Django 5.2.10 on 2026-01-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='main_app.tag'),
        ),
    ]
